### ISSUE TITLE
(re) Add entities

### ISSUE THREAD

**Issue by tgbetauser** [wjclub/telegram-bot-getids#10]
Pls re-add also entities :c

![](https://i.imgur.com/uwXyH21.jpg)

**Comment by jfowl** [comment]
ToDo for this:
- Filter irrelevant entities (bold, italic, code) out
- Put all text_link entities into an array
- Append the array to the Message-part

**Comment by jfowl** [comment]
implemented in 23ad9f4.

**Comment by tgbetauser** [comment]
Thanks
