### ISSUE TITLE
Add link to post as desktop client

### ISSUE THREAD

**Issue by mesb1** [wjclub/telegram-bot-getids#17]
Hi.

**Is your feature request related to a problem? Please describe.**
Its not a problem related, but behaviour of bot was changed after some restore few month ago.

**Describe the solution you'd like**
In first generation of bot, we can forward post from any channel.
Sometimes channels post that was reposted from another channel.
And bot gave us link to post just like desktop telegram client do.
This is useful for mobile client that still don't have that feature.
But todays getid bot gave us only link directly to post.

As example, thats the link to post, that was reposted by channel.
Created via desktop telegram client:
https://t.me/karaulny/147834

But when we forward post from that channel to getid bot, it shows us:
message_id: 13313
Its: https://t.me/bbbreaking/13313 message in original channel it was reposted from 

Thats would be greate to add functionality in addition that we already have.
Not change what we got now, just add someting like:
repost_message_id
And link as desktop telegram client do.

**Comment by jfowl** [comment]
I finally came around to work on this and it seams like this is not fixable. Why?
The bot does not receive the intermediary channel anymore. Take https://t.me/geekschannel/1159 as an example. It is a message from t.me/BotNews posted on t.me/GeeksChannel. When I forward it to a bot, this is the json it receives:
```json
{
    "update_id": 436041685,
    "message": {
        "message_id": 24558,
        "from": {
            "id": 317434635,
            "is_bot": false,
            "first_name": "Jonas",
            "last_name": "Fowl",
            "username": "jfowl",
            "language_code": "en"
        },
        "chat": {
            "id": 317434635,
            "first_name": "Jonas",
            "last_name": "Fowl",
            "username": "jfowl",
            "type": "private"
        },
        "date": 1562060139,
        "forward_from_chat": {
            "id": -1001004276399,
            "title": "BotNews",
            "username": "BotNews",
            "type": "channel"
        },
        "forward_from_message_id": 47,
        "forward_date": 1559383887,
        "text": "Introducing Bot API 4.3: Seamless Telegram Login for web services and more.\n\nFull changelog:\nhttps://core.telegram.org/bots/api-changelog#may-31-2019",
        "entities": [
            {
                "offset": 12,
                "length": 11,
                "type": "bold"
            },
            {
                "offset": 93,
                "length": 56,
                "type": "url"
            }
        ]
    }
}
```
The information about t.me/GeeksChannel is completely gone. I just can't extract it from what I receive as a bot. Sorry about that.
