### ISSUE TITLE
[Bug] Bot GetIDsBot is down

### ISSUE THREAD

**Issue by vladislav805** [wjclub/telegram-bot-getids#67]
**Describe the bug**
Bot t.me/GetIDsBot does not work now.

**Expected behavior**
Answer to any message, e.g., `/start`.

**Actual behavior**
_*nothing happens*_

**If you encountered the bug while using the bot with Telegram, where was it:**
- [x] @GetIDsBot
- [ ] @GetIDsDebugBot
- [ ] Another instance (self hosted, etc)

**To Reproduce**
Send any message to bot.

**Comment by jfowl** [comment]
Should work again. Thanks for reporting.

**Comment by erkantaylan** [comment]
Not working about, no respond from `/start` and `/about`

**Comment by jfowl** [comment]
> Not working again, no respond from `/start` and `/about`

Should be resolved soon. Logfiles filled up the storage and the monitoring did not kick in. Sorry.

**Comment by erkantaylan** [comment]
Fixed again.
