### ISSUE TITLE
[Bug] Bot GetIDsBot is down

### ISSUE THREAD

**Issue by lzk800** [wjclub/telegram-bot-getids#68]
**Describe the bug**
Bot t.me/GetIDsBot does not work now.

**Expected behavior**
Answer to any message, e.g., /start.

**If you encountered the bug while using the bot with Telegram, where was it:**
- [*] @GetIDsBot
- [ ] @GetIDsDebugBot
- [ ] Another instance (self hosted, etc)

**To Reproduce**
Send any message to bot.

**Comment by jfowl** [comment]
Should be resolved soon. Logfiles filled up the storage and the monitoring did not kick in. Sorry.
