### ISSUE TITLE
[Bug] X @usinfobot

### ISSUE THREAD

**Issue by Over777b** [wjclub/telegram-bot-getids#79]
**Describe the bug**

**Expected behavior**

**Screenshots**

**If you encountered the bug while using the bot with Telegram, where was it:**
- [x] @GetIDsBot
- [x] @GetIDsDebugBot
- [x] Another instance (self hosted, etc)

**To Reproduce**

**Additional context**

**Comment by jfowl** [comment]
I don't think that's a bug. But feel free to add it as an alternative in the Readme
